name: Build Hook

on: [push, pull_request]

jobs:
  mac:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-11, macos-12 ]
    steps:
    - uses: actions/checkout@v3
    - run: ./build.sh
      shell: bash
      env:
        OUTPUT_DIR: ${{ runner.temp }}
        QT_VERSION: 5.15.1
    - run: otool -L "$RUNNER_TEMP/build/qtbase/lib/QtNetwork.framework/Versions/5/QtNetwork"
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}
        path: ${{ runner.temp }}/build/qtbase/lib/QtNetwork.framework/Versions/5/QtNetwork
        if-no-files-found: error

  win:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-2019, windows-2022 ]
    steps:
    - uses: actions/checkout@v3
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64     # Matches Qt5Network.dll 5.15.2
       #toolset: 14.26  # Matches Qt5Network.dll 5.15.2
       #vsversion: 2019 # Matches Qt5Network.dll 5.15.2
    - run: rm -f /usr/bin/link && ./build.sh
      shell: bash
      env:
        QT_VERSION: 5.15.2
    - run: find "$GITHUB_WORKSPACE" -name 'Qt5Network.dll'
      shell: bash
    - run: find "$RUNNER_TEMP" -name 'Qt5Network.dll'
      shell: bash
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}
        path: ${{ runner.temp }}/build/qtbase/lib/Qt5Network.dll
        if-no-files-found: error
