name: Build Hook

on: [push, pull_request]

jobs:
  mac:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-11, macos-12 ]
    steps:
    - uses: actions/checkout@v3
    - run: ./build.sh
      shell: bash
      env:
        OUTPUT_DIR: ${{ runner.temp }}
        QT_VERSION: 5.15.1
    - uses: actions/upload-artifact@v3
      with:
        name: macOS
        path: ${{ runner.temp }}/build/qtbase/lib/QtNetwork.framework/Versions/5/QtNetwork
        if-no-files-found: error

  win:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-2019, windows-2022 ]
    steps:
    - run: dir 'C:\Program Files'
    - run: dir 'C:\Program Files\OpenSSL'
    - run: dir 'C:\Program Files\OpenSSL\include'
    - run: dir 'C:\Program Files\OpenSSL\lib'
    - uses: actions/checkout@v3
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64     # Matches Qt5Network.dll 5.15.2
        toolset: 14.26  # Matches Qt5Network.dll 5.15.2
        vsversion: 2019 # Matches Qt5Network.dll 5.15.2
    - run: ./build.sh
      shell: bash
      env:
        QT_VERSION: 5.15.2
    - uses: actions/upload-artifact@v3
      with:
        name: windows
        path: ${{ runner.temp }}/build/qtbase/lib/Qt5Network.dll
        if-no-files-found: error
